import Link from "next/link";

export const metadata = { title: "Admissions 2026–27 | Imam Institute", description: "Apply for BS Nursing admissions 2026–27 at Imam Institute of Nursing & Allied Health Sciences." };

const documents = ["Matriculation certificate", "Intermediate (Pre-Medical) certificate", "Character certificate", "CNIC or B-Form copy", "Recent passport-size photographs"];

export default function Admissions2026Page() {
  return <section className="bg-off-white"><div className="mx-auto max-w-5xl px-6 py-24 md:px-10"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-crimson">Admissions 2026–27</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.03em] text-navy text-display">Begin your nursing journey</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-ink-muted">Applications are open for the BS Nursing program. Join an institute grounded in academic excellence, clinical practice, and compassionate care.</p><div className="mt-12 grid gap-6 md:grid-cols-2"><div className="rounded-[1.75rem] bg-white p-8 shadow-sm"><h2 className="text-2xl font-semibold text-navy">Eligibility</h2><ul className="mt-5 list-disc space-y-3 pl-5 text-sm leading-7 text-ink-muted"><li>Intermediate Pre-Medical or equivalent qualification.</li><li>Minimum passing grades as required by current regulations.</li><li>Age and other requirements as per PNMC guidelines.</li></ul></div><div className="rounded-[1.75rem] bg-white p-8 shadow-sm"><h2 className="text-2xl font-semibold text-navy">Required documents</h2><ul className="mt-5 list-disc space-y-3 pl-5 text-sm leading-7 text-ink-muted">{documents.map((document) => <li key={document}>{document}</li>)}</ul></div></div><div className="mt-6 rounded-[1.75rem] bg-navy p-8 text-white md:flex md:items-center md:justify-between md:gap-8"><div><h2 className="text-2xl font-semibold">Ready to apply?</h2><p className="mt-2 text-sm leading-7 text-white/75">Submit an enquiry and our admissions team will guide you through the next steps.</p></div><Link href="/admissions/apply" className="mt-6 inline-flex rounded-sm bg-crimson px-6 py-3 text-sm font-semibold text-white transition hover:bg-crimson-dark md:mt-0">Apply Online</Link></div></div></section>;
}
