export const metadata = { title: "Downloads | Imam Institute", description: "Download forms and documents from Imam Institute." };

const documents = [
	{ title: "Admission application form - Page 1", description: "Official admission application form", href: "/images/FORMS/Application-form1.jpg", label: "Download" },
	{ title: "Admission application form - Page 2", description: "Official admission application form", href: "/images/FORMS/Application-form2.jpg", label: "Download" },
	{ title: "Required documents checklist", description: "Documents and undertaking requirements for admission", href: "/documents/required-documents-checklist.pdf", label: "Download PDF" },
	{ title: "BS Nursing prospectus", description: "Document coming soon", href: "", label: "Soon" },
	{ title: "Fee structure", description: "Document coming soon", href: "", label: "Soon" },
];

export default function DownloadsPage() { return <section className="bg-off-white"><div className="mx-auto max-w-5xl px-6 py-24 md:px-10"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-crimson">Resources</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.03em] text-navy text-display">Downloads</h1><p className="mt-4 max-w-3xl text-base leading-8 text-ink-muted">Forms and documents for applicants and students.</p><div className="mt-12 divide-y divide-border rounded-[1.75rem] border border-border bg-white px-7">{documents.map((document) => <div key={document.title} className="flex items-center justify-between gap-5 py-6"><div><h2 className="font-semibold text-navy">{document.title}</h2><p className="mt-1 text-sm text-ink-muted">{document.description}</p></div>{document.href ? <a href={document.href} target="_blank" rel="noreferrer" className="rounded-full bg-crimson px-3 py-1 text-xs font-semibold uppercase tracking-[0.15em] text-white">{document.label}</a> : <span className="rounded-full bg-navy-light px-3 py-1 text-xs font-semibold uppercase tracking-[0.15em] text-navy">{document.label}</span>}</div>)}<div className="flex items-center justify-between gap-5 py-6"><div><h2 className="font-semibold text-navy">HEC Curriculum BSN-MSN 2024</h2><p className="mt-1 text-sm text-ink-muted">Higher Education Commission curriculum document</p></div><a href="/images/curriculum/HEC%20Curriculum%20BSN-MSN%202024.pdf" target="_blank" rel="noreferrer" className="rounded-full bg-crimson px-3 py-1 text-xs font-semibold uppercase tracking-[0.15em] text-white">Download PDF</a></div></div></div></section>; }
